# Generated by Django 2.2.22 on 2021-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('requested_by', models.CharField(max_length=80)),
                ('completed_by', models.CharField(max_length=80)),
            ],
        ),
    ]
