# Generated by Django 3.2.4 on 2021-06-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='complete_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='completed_by',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='requested_by',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
